baseURL = "https://dcpri.me/"
languageCode = "en-us"
title = "DCPrime's Blog"
enableEmoji = true
theme = "PaperMod"
[params]
  description = "Blog"
  copyright = "Copyright © 2022 Darshil Chanpura"
  dark = "auto"
  highlight = true
  mainSections = ["posts"]
  
  stylesheets = ["/css/fontawesome.min.css", "/css/brands.min.css", "/css/custom.css"]

  [params.plausible]
    enabled = true
    domain = "dcpri.me"
    src = "https://t.dcpri.me/js/plausible.js"

  [[params.links]]
    link = "https://github.com/dtchanpura"
    logoEnabled = true
    logoClass = "fab fa-github-square"
  [[params.links]]
    link = "https://twitter.com/dtchanpura"
    logoEnabled = true
    logoClass = "fab fa-twitter-square"
  [[params.links]]
    link = "https://git.dcpri.me/explore"
    logoEnabled = true
    logoClass = "fab fa-git-square"
  [params.homeInfoParams]
    Title = "DCPrime's Blog"
    Content = "Hello everyone! I am Darshil Chanpura, working as a DevOps engineer at IQM Corporation and a geek who is into many things related to many different platforms.\n<br><br>\nYou'll find a lot of learnings over the years here."
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/dtchanpura"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/dtchanpura"
  [[params.socialIcons]]
    name = "mastodon"
    url = "https://mastodon.online/@dtchanpura"
  [[params.socialIcons]]
    name = "git"
    url = "https://git.dcpri.me/"
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects/"
    weight = 30

[permalinks]
  posts = "/:sections[1:]/:year/:month/:day/:title"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
  
  [markup.tableOfContents]
    ordered = true

